# -*- coding: utf-8 -*-
"""ACD_data_proyecto_limpieza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgQDKHX66x3yyJjYssLAQvV0mTbas937

# 1. Extracción (Extract)
Dado que muchos sistemas de tickets (como Zendesk o Freshdesk) exportan archivos `.xls` que en realidad son `XML Spreadsheet 2003`, usar `pd.read_excel()` nos arrojaría un error. Este bloque usa `xml.etree.ElementTree` para parsear ese falso Excel y convertirlo en un DataFrame decente.
"""

from lxml import etree
import pandas as pd
import numpy as np

# Ruta del archivo
file_path = "9000678639_tickets-April-24-2026-21_21.xls"

print("Iniciando extracción con parser tolerante a fallos (esto puede tardar unos segundos con +1.3M de líneas)...")

# El parser con recover=True ignora los errores de sintaxis del XML
parser = etree.XMLParser(recover=True, huge_tree=True)
tree = etree.parse(file_path, parser=parser)
root = tree.getroot()

# El namespace de Microsoft
ns = {'ss': 'urn:schemas-microsoft-com:office:spreadsheet'}

data = []
for row in root.findall('.//ss:Row', namespaces=ns):
    row_data = []
    for cell in row.findall('.//ss:Cell', namespaces=ns):
        data_elem = cell.find('ss:Data', namespaces=ns)
        row_data.append(data_elem.text if data_elem is not None else None)

    # Solo agregamos la fila si tiene al menos un dato (evita filas fantasma)
    if any(row_data):
        data.append(row_data)

print("XML procesado. Construyendo DataFrame...")

# Creamos el DataFrame

if len(data) > 1:
    df_raw = pd.DataFrame(data[1:], columns=data[0])
    print(f"¡Éxito! Dimensiones iniciales: {df_raw.shape}")
    display(df_raw.head(3))
else:
    print("Ocurrió un error, no se encontraron datos.")

"""# 2. Transformación (Transform) - Limpieza Estructural
Los espacios y las mayúsculas en los nombres de las columnas no son adecuados en el análisis de datos. Aquí vamos a estandarizar los nombres, eliminar columnas completamente vacías o inútiles (como 'Firma del cliente') y filtrar los datos para que coincidan con la clasificación oficial del manual de Promotick: Solo Incidentes y Requerimientos.
"""

df = df_raw.copy()
pd.set_option('display.max_columns', None)
# 1. Limpiamos los nombres de las columnas

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')

# 2. Convertimos strings vacíos o con puros espacios a Nulos reales (NaN)

df = df.replace(r'^\s*$', np.nan, regex=True)

# 3. Ahora sí, borramos las columnas que son 100% nulas

df = df.dropna(axis=1, how='all')

# 4. Eliminamos columnas manuales
columnas_basura = ['firma_del_cliente', 'resultados_de_la_encuesta']
df = df.drop(columns=[col for col in columnas_basura if col in df.columns], errors='ignore')

# 5. Estandarizamos mayúsculas en los campos clave

if 'tipo' in df.columns:
    df['tipo'] = df['tipo'].astype(str).str.strip().str.capitalize()

if 'prioridad' in df.columns:
    df['prioridad'] = df['prioridad'].astype(str).str.strip().str.capitalize()

print("Columnas que quedaron:")
print(df.columns.tolist())

df

"""# 3. Transformación - Tiempos y Fechas
Para calcular los indicadores operacionales como "Tiempo Promedio de Atención" o "Tiempo de Primera Respuesta", necesitamos que los strings de fecha sean objetos `datetime`.
Convertiremos las fechas clave y llenaremos los vacíos lógicos.
"""

# Convertimos las columnas de fechas principales
cols_fechas = ['tiempo_de_creación', 'tiempo_de_resolución', 'hora_de_cierre', 'última_hora_de_la_actualización']

for col in cols_fechas:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')

# Tiempo desde que se creó hasta que se resolvió (en horas)
if 'tiempo_de_resolución' in df.columns and 'tiempo_de_creación' in df.columns:
    df['lead_time_horas'] = ((df['tiempo_de_resolución'] - df['tiempo_de_creación']).dt.total_seconds() / 3600).round(4)

# Bandera para saber si el ticket sigue abierto (Backlog)
# Según el manual, backlog es la diferencia entre abiertos y cerrados.
df['esta_abierto'] = df['estado'].apply(lambda x: 1 if str(x).lower() not in ['cerrado', 'resuelto', 'closed', 'resolved'] else 0)

df[['tiempo_de_creación', 'tiempo_de_resolución', 'lead_time_horas', 'esta_abierto']].head()

"""# 4. Enriquecimiento de Datos y KPIs
De acuerdo con los "Indicadores de Gestión" del manual, necesitamos poder medir el Cumplimiento de SLA y el Backlog Crítico (Tickets de alta prioridad pendientes).
Aquí creamos esas métricas para que cuando se use Seaborn o Plotly, los gráficos sean fáciles de realizar.
"""

# Backlog Crítico: Alta prioridad + Abierto

if 'prioridad' in df.columns:
    df['backlog_critico'] = np.where((df['esta_abierto'] == 1) & (df['prioridad'] == 'Alta'), 1, 0)

# Cumplimiento de SLA (asumiendo que 'vencidas_hasta_ahora' es un booleano o indicador del sistema)
# Si no existe, usamos 'estado_de_resolución'
if 'estado_de_resolución' in df.columns:
    df['incumple_sla'] = df['estado_de_resolución'].apply(lambda x: 1 if str(x).lower() in ['sla violated'] else 0)
    df['cumple_sla'] = 1 - df['incumple_sla']

# Extraemos el mes y el día de la semana de la creación
df['mes_creacion'] = df['tiempo_de_creación'].dt.to_period('M')
df['dia_semana_creacion'] = df['tiempo_de_creación'].dt.day_name()

print(f"Total de Backlog Crítico actual: {df['backlog_critico'].sum()}")

"""# 5.  Validación y limpieza final del dataset

Después de la creación de variables, se realiza una última etapa de limpieza del dataset con el objetivo de eliminar variables que no aportan valor analítico o que han sido descontinuadas según lo indicado por el representante de Promotick. Esto permite reducir ruido en los datos y mantener únicamente información relevante para el análisis.

Se eliminan las siguientes variables:

- "tiempo_de_seguimiento": no utilizada en los procesos actuales.
- "estado_de_la_aprobación": campo asociado a aprobaciones no relevante  para el análisis.
- "jefe_de_ti_que_aprueba_la_solicitud": variable administrativa sin valor analítico.
- "producto": columna sin información (vacía).
- "id_de_contacto": identificador no necesario para el análisis de negocio.
"""

df.drop(columns=[ "tiempo_de_seguimiento", "estado_de_la_aprobación", "jefe_de_ti_que_aprueba_la_solicitud","producto","id_de_contacto"],
        inplace=True)

"""# 6. Asignación de tipos de datos
En esta etapa se asigna a cada variable el tipo de dato más adecuado según su naturaleza (numérico, categórico, fecha o duración). Esto permite asegurar la correcta interpretación de los datos y su uso en análisis posteriores.
"""

# Columnas numericas

cols_numericas = [
    'interacciones_de_agente',
    'interacciones_de_cliente',
    'tiempo_empleado',
    'lead_time_horas'
]

for col in cols_numericas:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Fechas

cols_fechas = [
    'inicio_de_atencion',
    'fin_de_atencion',
    'tiempo_de_respuesta_inicial',
    'tiempo_de_creación',
    'tiempo_de_resolución',
    'hora_de_cierre',
    'última_hora_de_la_actualización',
    'vencidas_hasta_ahora'
]

for col in cols_fechas:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')

cols_duracion = [
    'primer_tiempo_de_respuesta_en_horas',
    'tiempo_de_resolución_en_horas'
]

for col in cols_duracion:
    if col in df.columns:
        df[col] = pd.to_timedelta(df[col], errors='coerce')



# Columnas binarias

cols_sla = [
    'esta_abierto',
    'backlog_critico',
    'incumple_sla',
    'cumple_sla'
]

for col in cols_sla:
    if col in df.columns:
        df[col] = df[col].astype('int')

cols_excluir = [
    'id_del_ticket',
    'id_de_contacto',
    'asunto',
    'nombre_completo',
    'etiquetas',
    'dependencias'
]

print(df.info())

"""# 7. Carga (Load) - Exportar la Data Limpia
La limpieza está lista. Guardemos esto como un `.csv`. Con esto, la data ya está lista para usarse.
"""

# Guardamos en un archivo CSV limpio, separado por comas
clean_file_name = "tickets_promotick_clean.csv"
df.to_csv(clean_file_name, index=False, encoding='utf-8')

print(f"¡Éxito! Datos limpios exportados a {clean_file_name}")
print("Aquí un resumen de tu dataset final:")
df.info()

df

"""# 8. Creamos el diccionario de datos"""

diccionario = []

if 'id_del_ticket' in df.columns:
    diccionario.append({
        "variable": "id_del_ticket",
        "tipo": "Identificador",
        "min_id": df['id_del_ticket'].min(),
        "max_id": df['id_del_ticket'].max(),
        "n_unicos": df['id_del_ticket'].nunique()
    })


# Numéricas

num_cols = df.select_dtypes(include=['int64', 'float64']).columns

num_cols = [c for c in num_cols if c not in ['esta_abierto', 'backlog_critico', 'incumple_sla', 'cumple_sla']]

for col in num_cols:
    diccionario.append({
        "variable": col,
        "tipo": "Numérico",
        "min": df[col].min(),
        "max": df[col].max(),
        "valores_unicos": df[col].nunique()
    })


# 2. FECHAS
date_cols = df.select_dtypes(include=['datetime64[ns]']).columns

for col in date_cols:
    diccionario.append({
        "variable": col,
        "tipo": "Fecha",
        "min_fecha": df[col].min(),
        "max_fecha": df[col].max()
    })


# 3. CATEGÓRICAS
cat_cols = df.select_dtypes(include=['object']).columns

cat_cols = [c for c in cat_cols if c != 'id_del_ticket']

for col in cat_cols:
    diccionario.append({
        "variable": col,
        "tipo": "Categórico",
        "n_valores": df[col].nunique(),
        "valores": df[col].dropna().unique()[:10]
    })


df_diccionario = pd.DataFrame(diccionario)
df_diccionario